### ISSUE TITLE
.6 -.8 upgrade issue?

### ISSUE THREAD

**Issue by ferventgeek** [bpaauwe/udi-sonos-poly#1]
Bob, great node server, thx! Question on upgrade. Previously I hit the upgrade button in the NodeServer store list in Polyglot, bounced the server in the dashboard, done and done. This time however going from 2.0.6 to 2.0.8 it shows git download complete, but the upgrade doesn't happen. It keeps showing 2.0.6 in the details page.

Troubleshooting:

1. With and without "upload to ISY"
2. ISY manual reboot (per result dialog)
3. Bounce the Polsy server

Any advice appreciated, I'm sure I'm doing something dumb.

**Comment by bpaauwe** [comment]
Thanks, but I didn't write the node server.  I just took it over to fix an issue when the original author decided not to maintain it anymore.

I don't have any suggestions other than to check the log files.  I don't use PG2 anymore.

**Comment by ferventgeek** [comment]
Ok, thx. If I find an issue I'll create a PR, Thanks again.

**Comment by ferventgeek** [comment]
Follow up. Does [/profile/version.txt](https://github.com/bpaauwe/udi-sonos-poly/blob/master/profile/version.txt) need to match 2.0.8? It's still 2.0.6.

And I'm assuming my Polisy is v2. There's no separate PG version displayed.

**Comment by bpaauwe** [comment]
The versison.txt file isn't used (I don't think).   As I said, I don't really have anything to do with this node server other than fixing an issue in it a while back.
